# Generated by Django 5.1.3 on 2024-11-07 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('position', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='players/')),
                ('total_points', models.IntegerField(default=0)),
                ('total_goals', models.IntegerField(default=0)),
                ('total_defenses', models.IntegerField(default=0)),
                ('total_assists', models.IntegerField(default=0)),
                ('total_tackles', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_losses', models.IntegerField(default=0)),
                ('total_draws', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDayPontuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('defenses', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('match_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matchday')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='best_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_player', to='app.player'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('total_best_user', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('ala_direita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ala_direita', to='app.player')),
                ('ala_esquerda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ala_esquerda', to='app.player')),
                ('fixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixo', to='app.player')),
                ('goleiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goleiro', to='app.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.matchday')),
                ('pivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pivo', to='app.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='matchday',
            name='best_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_user', to='app.userprofile'),
        ),
    ]
